Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "2024"
      vb.cpus = 1
    end
  
    config.vm.define "adminstuff" do |adminstuff|
      adminstuff.vm.box = "ubuntu/focal64"
      adminstuff.vm.provider "virtualbox" do |vb|
        vb.name = "adminstuff"
      end
      adminstuff.vm.network "private_network", ip: "192.168.3.100"
      adminstuff.vm.hostname = "adminstuff"
    end

    config.vm.define "lb" do |lb|
        lb.vm.box = "ubuntu/focal64"
        lb.vm.provider "virtualbox" do |vb|
          vb.name = "lb"
        end
        lb.vm.network "private_network", ip: "192.168.3.200"
        lb.vm.hostname = "lb"
    end

    config.vm.define "registry" do |registry|
      registry.vm.box = "ubuntu/focal64"
      registry.vm.provider "virtualbox" do |vb|
        vb.name = "registry"
      end
      registry.vm.network "private_network", ip: "192.168.3.201"
      registry.vm.hostname = "registry"
    end

    config.vm.define "master1" do |master1|
        master1.vm.box = "ubuntu/focal64"
        master1.vm.provider "virtualbox" do |vb|
          vb.name = "master1"
      end
        master1.vm.network "private_network", ip: "192.168.3.101"
        master1.vm.hostname = "master1"
    end

    config.vm.define "master2" do |master2|
        master2.vm.box = "ubuntu/focal64"
        master2.vm.provider "virtualbox" do |vb|
          vb.name = "master2"
      end
        master2.vm.network "private_network", ip: "192.168.3.102"
        master2.vm.hostname = "master2"
    end

    config.vm.define "master3" do |master3|
        master3.vm.box = "ubuntu/focal64"
        master3.vm.provider "virtualbox" do |vb|
          vb.name = "master3"
      end
        master3.vm.network "private_network", ip: "192.168.3.103"
        master3.vm.hostname = "master3"
    end
    
    config.vm.define "worker1" do |worker1|
        worker1.vm.box = "ubuntu/focal64"
        worker1.vm.provider "virtualbox" do |vb|
          vb.name = "worker1"
          vb.memory = "3072"
          vb.cpus = 2
      end
        worker1.vm.network "private_network", ip: "192.168.3.104"
        worker1.vm.hostname = "worker1"
    end

    config.vm.define "worker2" do |worker2|
        worker2.vm.box = "ubuntu/focal64"
        worker2.vm.provider "virtualbox" do |vb|
          vb.name = "worker2"
          vb.memory = "3072"
          vb.cpus = 2
      end
        worker2.vm.network "private_network", ip: "192.168.3.105"
        worker2.vm.hostname = "worker2"
    end
  end
  