apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-elastic
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    name: elasticsearch-data-elastic-es-default-0
    namespace: services
  local:
    path: /opt/elastic
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node4
