apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-redis-0
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 64Mi
  claimRef:
    name: data-redis-0
    namespace: redis
  local:
    path: /opt/redis-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node4
---
 kind: PersistentVolumeClaim
 apiVersion: v1
 metadata:
   name: data-redis-0
   namespace: redis
 spec:
   storageClassName: standard
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 64Mi                
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-redis-1
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 64Mi
  claimRef:
    name: data-redis-1
    namespace: redis
  local:
    path: /opt/redis-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node5
---                  
 kind: PersistentVolumeClaim
 apiVersion: v1
 metadata:
   name: data-redis-1
   namespace: redis
 spec:
   storageClassName: standard
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 64Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-redis-2
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 64Mi
  claimRef:
    name: data-redis-2
    namespace: redis
  local:
    path: /opt/redis-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node5
---
 kind: PersistentVolumeClaim
 apiVersion: v1
 metadata:
   name: data-redis-2
   namespace: redis
 spec:
   storageClassName: standard
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 64Mi                  
