all:
  hosts:
    node1:
      ansible_host: 192.168.3.101
      ip: 192.168.3.101
      access_ip: 192.168.3.101
    node2:
      ansible_host: 192.168.3.102
      ip: 192.168.3.102
      access_ip: 192.168.3.102
    node3:
      ansible_host: 192.168.3.103
      ip: 192.168.3.103
      access_ip: 192.168.3.103
    node4:
      ansible_host: 192.168.3.104
      ip: 192.168.3.104
      access_ip: 192.168.3.104
    node5:
      ansible_host: 192.168.3.105
      ip: 192.168.3.105
      access_ip: 192.168.3.105
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
        node3:
    kube_node:
      hosts:
        node4:
        node5:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
